import type { ModuleReadiness } from "@/lib/acnetrex/module-result";

export type ModuleCategory =
  | "Account"
  | "Daily Intelligence"
  | "Face Intelligence"
  | "Product Intelligence"
  | "AI/ML Intelligence"
  | "Treatment"
  | "Reports"
  | "Privacy"
  | "Gamification"
  | "Native/Device"
  | "Research";

export type ModuleSurface =
  | "route"
  | "form"
  | "history"
  | "service_adapter"
  | "persistence_contract"
  | "ai_contract"
  | "durable_conversation_api"
  | "readiness_state"
  | "export_state";

export type AcneTrexModule = {
  id: string;
  name: string;
  route: string;
  category: ModuleCategory;
  description: string;
  prdPriority: "P0" | "P1" | "P2";
  requiresAuth: boolean;
  requiresOnboarding: boolean;
  requiresConsentScopes: string[];
  dataTables: string[];
  storageBuckets: string[];
  serviceStatus: ModuleReadiness;
  readinessStatus: ModuleReadiness;
  implementedSurfaces: ModuleSurface[];
  missingSurfaces: string[];
  nextAction: string;
};

const allSurfaces: ModuleSurface[] = [
  "route",
  "form",
  "history",
  "service_adapter",
  "persistence_contract",
  "ai_contract",
  "readiness_state",
];

export const ACNETREX_MODULES: AcneTrexModule[] = [
  {
    id: "auth",
    name: "Account Access",
    route: "/auth",
    category: "Account",
    description: "Account-first entry with Supabase-aware session and honest unavailable states.",
    prdPriority: "P0",
    requiresAuth: false,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["users", "consent_settings"],
    storageBuckets: [],
    serviceStatus: "not_configured",
    readinessStatus: "auth_required",
    implementedSurfaces: ["route", "service_adapter", "readiness_state"],
    missingSurfaces: ["Live signed-session validation", "native secure auth storage"],
    nextAction: "Validate Supabase Auth in production and bridge native session storage.",
  },
  {
    id: "onboarding",
    name: "Skin History Onboarding",
    route: "/onboarding",
    category: "Account",
    description: "Mandatory baseline, Skin History, meal frequency, sleep, routine, treatment, and consent capture.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: ["profile_baseline"],
    dataTables: ["profile_sections", "profile_version_history", "consent_settings"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Live write/read verification", "expanded Skin History E2E"],
    nextAction: "Persist and reload onboarding sections with a signed Supabase session.",
  },
  {
    id: "profile",
    name: "Professional Profile",
    route: "/profile",
    category: "Reports",
    description: "Versioned professional profile sections used by reports and provider review.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["professional_profile"],
    dataTables: ["profile_sections", "profile_version_history", "profile_audit_events"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract"],
    missingSurfaces: ["Provider-facing polish", "live RLS verification"],
    nextAction: "Verify profile update API against production Supabase.",
  },
  {
    id: "privacy",
    name: "Consent and Privacy Center",
    route: "/privacy",
    category: "Privacy",
    description: "Consent controls for anonymous learning, raw images, notifications, exports, and deletion.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["consent_settings", "consent_audit_events", "deletion_requests"],
    storageBuckets: ["face-scans-raw", "reports", "skin-twin"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Revocation E2E", "storage lifecycle verification"],
    nextAction: "Verify raw image retention and deletion lifecycle with private buckets.",
  },
  {
    id: "readiness",
    name: "Readiness Console",
    route: "/readiness",
    category: "AI/ML Intelligence",
    description: "Operational status for data sufficiency, cloud ML, local fallback, telemetry, and evidence tools.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["ml_telemetry"],
    dataTables: ["ml_runtime_events"],
    storageBuckets: [],
    serviceStatus: "not_configured",
    readinessStatus: "not_configured",
    implementedSurfaces: ["route", "service_adapter", "ai_contract", "readiness_state"],
    missingSurfaces: ["Live Cloud Run health", "Vertex prediction verification"],
    nextAction: "Connect production Cloud Run health to engine-status telemetry.",
  },
  {
    id: "sleepderm",
    name: "SleepDerm",
    route: "/log/sleep",
    category: "Daily Intelligence",
    description: "Sleep duration, debt, midpoint, regularity, recovery opportunity, and acne-readiness contribution.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["sleep_logs"],
    dataTables: ["daily_logs", "sleep_logs"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Live sleep_logs write/read", "optimization plan after longitudinal records"],
    nextAction: "Validate durable save/reload against signed Supabase session.",
  },
  {
    id: "dermdiet",
    name: "DermDiet",
    route: "/log/food",
    category: "Daily Intelligence",
    description: "Meal baseline, snack sub-events, category exposure windows, and non-judgmental food pattern tracking.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["food_logs"],
    dataTables: ["food_logs", "daily_logs"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Live food_logs write/read", "association analytics after outcome records"],
    nextAction: "Verify same-day meal baseline and snack inserts in Supabase.",
  },
  {
    id: "stress",
    name: "Stress Log",
    route: "/log/stress",
    category: "Daily Intelligence",
    description: "Daily stress intensity, context, recovery practices, and TriggerGraph contribution.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["daily_logs"],
    dataTables: ["daily_logs"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Dedicated stress_logs table", "lagged association model"],
    nextAction: "Persist stress inputs and expose feature snapshots.",
  },
  {
    id: "activity",
    name: "Activity and SweatFlow",
    route: "/log/activity",
    category: "Daily Intelligence",
    description: "Exercise, sweat exposure, post-activity cleansing, heat, and occlusion context.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["daily_logs"],
    dataTables: ["daily_logs"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "persistence_contract", "readiness_state"],
    missingSurfaces: ["SweatFlow feature extraction", "weather-aware correlation"],
    nextAction: "Add activity feature extraction into TriggerGraph.",
  },
  {
    id: "hydration",
    name: "Hydration Log",
    route: "/log/hydration",
    category: "Daily Intelligence",
    description: "Hydration proxy and consistency inputs for reports and Skin Twin variables.",
    prdPriority: "P2",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["daily_logs"],
    dataTables: ["daily_logs"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Dedicated hydration records", "provider report summaries"],
    nextAction: "Map hydration entries to daily_logs and feature snapshots.",
  },
  {
    id: "cycle",
    name: "CycleSync",
    route: "/log/cycle",
    category: "Daily Intelligence",
    description: "Optional hormonal-cycle context with consent-aware confounder handling.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["cycle_context"],
    dataTables: ["daily_logs"],
    storageBuckets: [],
    serviceStatus: "consent_required",
    readinessStatus: "consent_required",
    implementedSurfaces: ["route", "form", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Dedicated cycle_logs table", "privacy revocation flow"],
    nextAction: "Add opt-in cycle context persistence and deletion controls.",
  },
  {
    id: "contact",
    name: "ContactGuard",
    route: "/log/contact",
    category: "Daily Intelligence",
    description: "Mask, helmet, pillowcase, phone, touching, picking, and occlusion exposure tracking.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["daily_logs"],
    dataTables: ["daily_logs"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Contact exposure feature family", "BarrierGuard integration"],
    nextAction: "Persist contact exposures and link to zone flares.",
  },
  {
    id: "routine",
    name: "Routine Log",
    route: "/log/routine",
    category: "Daily Intelligence",
    description: "Cleanser, moisturizer, sunscreen, exfoliation, product changes, and consistency tracking.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["routine_logs"],
    dataTables: ["daily_logs", "profile_sections"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Routine-specific table", "FormulaLens product joins"],
    nextAction: "Connect routine entries to product history and treatment tolerance.",
  },
  {
    id: "treatment-log",
    name: "Treatment Log",
    route: "/log/treatment",
    category: "Treatment",
    description: "Treatment use, missed dose, irritation, tolerance, and provider-directed status.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["treatment_logs"],
    dataTables: ["treatment_plans", "treatment_checkins"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Live treatment check-in E2E", "safety escalation workflow"],
    nextAction: "Generate task-board items from active treatment schedules.",
  },
  {
    id: "skin-state",
    name: "Skin State Journal",
    route: "/log/skin-state",
    category: "Daily Intelligence",
    description: "Daily observed lesion, oiliness, redness, PIH/PIE, barrier, and flare/recovery labels.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["skin_state_logs"],
    dataTables: ["daily_logs", "face_atlas_scans"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Dedicated skin_state_logs table", "FaceAtlas-derived merge"],
    nextAction: "Persist structured skin outcomes for TriggerGraph and Skin Twin.",
  },
  {
    id: "face-atlas",
    name: "FaceAtlas",
    route: "/face-atlas",
    category: "Face Intelligence",
    description: "Five-angle capture, private storage, annotation-first lesion labels, zones, and disagreement handling.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["face_scans", "raw_image_retention"],
    dataTables: ["face_atlas_scans", "face_scans", "annotations"],
    storageBuckets: ["face-scans-raw"],
    serviceStatus: "queued_for_cloud",
    readinessStatus: "queued_for_cloud",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Live camera upload", "cloud lesion inference", "skin-tone image quality validation"],
    nextAction: "Verify private upload URLs and queue Cloud Run analysis.",
  },
  {
    id: "face-atlas-capture",
    name: "FaceAtlas Capture",
    route: "/face-atlas/capture",
    category: "Face Intelligence",
    description: "Angle checklist for front, left, right, chin-up, and forehead capture.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["face_scans"],
    dataTables: ["face_scans"],
    storageBuckets: ["face-scans-raw"],
    serviceStatus: "queued_for_cloud",
    readinessStatus: "queued_for_cloud",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "ai_contract", "readiness_state"],
    missingSurfaces: ["Native camera bridge", "signed upload live verification"],
    nextAction: "Bridge browser/native capture to private Supabase storage.",
  },
  {
    id: "face-atlas-annotations",
    name: "FaceAtlas Annotations",
    route: "/face-atlas/annotations",
    category: "Face Intelligence",
    description: "User-guided lesion labels, zones, certainty, and model-user disagreement records.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["face_scans"],
    dataTables: ["annotations", "face_scans"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Annotation canvas", "model comparison after inference"],
    nextAction: "Persist annotation records and disagreement feedback.",
  },
  {
    id: "face-atlas-history",
    name: "FaceAtlas History",
    route: "/face-atlas/history",
    category: "Face Intelligence",
    description: "Longitudinal scan, annotation, raw-retention, deletion, and queued-analysis history.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["face_scans"],
    dataTables: ["face_atlas_scans", "face_scans", "annotations"],
    storageBuckets: ["face-scans-raw"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "history", "service_adapter", "persistence_contract", "ai_contract", "readiness_state"],
    missingSurfaces: ["Live scan list verification", "raw-image deletion audit"],
    nextAction: "Load scan history from user-owned FaceAtlas tables and expose deletion state.",
  },
  {
    id: "skin-twin",
    name: "Skin Twin Lab",
    route: "/skin-twin",
    category: "AI/ML Intelligence",
    description: "Scenario readiness, active-variable simulation contracts, uncertainty bands, and derived-only visualization.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["skin_twin"],
    dataTables: ["skin_twin_snapshots", "forecast_summaries", "face_atlas_scans", "daily_logs"],
    storageBuckets: ["skin-twin"],
    serviceStatus: "ml_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Cloud simulation endpoint", "saved scenario model table", "visual projection engine"],
    nextAction: "Use real feature snapshots to request simulations through /api/ml/predict.",
  },
  {
    id: "skin-twin-scenarios",
    name: "Skin Twin Scenarios",
    route: "/skin-twin/scenarios",
    category: "AI/ML Intelligence",
    description: "Scenario variables for sleep, food, stress, treatment, routine, weather, contact, and picking/touching.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["skin_twin"],
    dataTables: ["skin_twin_snapshots"],
    storageBuckets: ["skin-twin"],
    serviceStatus: "insufficient_data",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract", "ai_contract"],
    missingSurfaces: ["Counterfactual model validation", "provider-review custom timeline"],
    nextAction: "Save validated draft scenarios and block projections until sufficient data exists.",
  },
  {
    id: "skin-twin-history",
    name: "Skin Twin History",
    route: "/skin-twin/history",
    category: "AI/ML Intelligence",
    description: "Saved and versioned scenario records with confidence, uncertainty, source refs, and model version state.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["skin_twin"],
    dataTables: ["skin_twin_snapshots", "ml_analysis_results"],
    storageBuckets: ["skin-twin"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "history", "service_adapter", "persistence_contract", "ai_contract", "readiness_state"],
    missingSurfaces: ["Versioned scenario table", "cloud simulation result persistence"],
    nextAction: "Load saved scenarios and label derived-only visualization state.",
  },
  {
    id: "cutisai",
    name: "CutisAI",
    route: "/cutisai",
    category: "AI/ML Intelligence",
    description: "Context-aware assistant with memory, evidence retrieval, backend tools, and no-diagnosis safety rules.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["cutisai_memory"],
    dataTables: ["cutisai_conversations", "user_memory_events", "memory_retrieval_logs"],
    storageBuckets: [],
    serviceStatus: "evidence_unavailable",
    readinessStatus: "not_configured",
      implementedSurfaces: ["route", "form", "service_adapter", "ai_contract", "readiness_state", "durable_conversation_api"],
      missingSurfaces: ["Backend tool execution", "evidence retrieval service", "assistant generation worker"],
    nextAction: "Persist conversations and use engine status for honest unavailable responses.",
  },
  {
    id: "ai-workspace",
    name: "AI Workspace",
    route: "/ai",
    category: "AI/ML Intelligence",
    description: "Unified entry for CutisAI, engine readiness, TriggerGraph, forecasting, Skin Twin, and evidence status.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["ml_analysis"],
    dataTables: ["ml_runtime_events", "ml_analysis_jobs", "ml_analysis_results"],
    storageBuckets: [],
    serviceStatus: "not_configured",
    readinessStatus: "not_configured",
    implementedSurfaces: ["route", "service_adapter", "ai_contract", "readiness_state"],
    missingSurfaces: ["Cloud Run live verification", "local model packaging", "result persistence"],
    nextAction: "Use the readiness console and /api/ml/predict as the only intelligence entrypoints.",
  },
  {
    id: "intelligence",
    name: "Intelligence Center",
    route: "/intelligence",
    category: "AI/ML Intelligence",
    description: "Cross-module intelligence surface for features, model outputs, telemetry, and no-fabrication status.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["ml_analysis"],
    dataTables: ["ml_feature_snapshots", "intelligence_events", "ml_runtime_events"],
    storageBuckets: [],
    serviceStatus: "insufficient_data",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "history", "service_adapter", "ai_contract", "readiness_state"],
    missingSurfaces: ["Feature snapshot table verification", "model result timeline"],
    nextAction: "Persist shared feature snapshots from SleepDerm, DermDiet, FaceAtlas, and treatment records.",
  },
  {
    id: "triggergraph",
    name: "TriggerGraph",
    route: "/triggers",
    category: "AI/ML Intelligence",
    description: "Lagged associations, confounder flags, hypothesis confidence, and correlation-not-causation language.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["ml_analysis"],
    dataTables: ["trigger_hypotheses", "ml_feature_snapshots"],
    storageBuckets: [],
    serviceStatus: "insufficient_data",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Minimum 14-30 day data window", "lagged regression engine"],
    nextAction: "Create feature snapshots from logs and skin outcomes.",
  },
  {
    id: "forecast",
    name: "Forecasting",
    route: "/forecast",
    category: "AI/ML Intelligence",
    description: "3, 7, 14, and 30-day forecast readiness, uncertainty, and forecast-error tracking.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["ml_analysis"],
    dataTables: ["forecast_summaries", "ml_analysis_results"],
    storageBuckets: [],
    serviceStatus: "insufficient_data",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Forecast model validation", "outcome backtesting"],
    nextAction: "Persist forecast jobs through ML proxy once Cloud Run is live.",
  },
  {
    id: "barrier",
    name: "BarrierGuard",
    route: "/barrier",
    category: "Product Intelligence",
    description: "Barrier symptom inputs, routine compatibility, irritation caution, and treatment tolerance context.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["skin_state_logs", "routine_logs"],
    dataTables: ["daily_logs", "profile_sections"],
    storageBuckets: [],
    serviceStatus: "insufficient_data",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Barrier-specific trend model", "FormulaLens ingredient cross-checks"],
    nextAction: "Link barrier symptoms to routine and treatment changes.",
  },
  {
    id: "products",
    name: "Product History",
    route: "/products",
    category: "Product Intelligence",
    description: "Manual product entry, ingredient list capture, routine history, and FormulaLens readiness.",
    prdPriority: "P2",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["products"],
    dataTables: ["products", "product_ingredients", "profile_sections"],
    storageBuckets: [],
    serviceStatus: "not_configured",
    readinessStatus: "not_configured",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["User product history table", "barcode/OCR provider"],
    nextAction: "Add manual product history persistence before OCR/barcode integration.",
  },
  {
    id: "formula-lens",
    name: "FormulaLens",
    route: "/formula-lens",
    category: "Product Intelligence",
    description: "Ingredient search, manual entry, OCR/barcode unavailable states, and routine conflict checks.",
    prdPriority: "P2",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["products"],
    dataTables: ["products", "product_ingredients"],
    storageBuckets: [],
    serviceStatus: "not_configured",
    readinessStatus: "not_configured",
    implementedSurfaces: ["route", "form", "service_adapter", "ai_contract", "readiness_state"],
    missingSurfaces: ["OCR", "barcode search", "evidence-backed ingredient rules"],
    nextAction: "Connect curated ingredient database and OCR provider.",
  },
  {
    id: "climate",
    name: "ClimateSkin Radar",
    route: "/climate",
    category: "Daily Intelligence",
    description: "Weather, heat, humidity, UV, AQI, and location-precision-aware trigger context.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["weather_context"],
    dataTables: ["weather_snapshots"],
    storageBuckets: [],
    serviceStatus: "not_configured",
    readinessStatus: "not_configured",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Weather provider", "location permission bridge"],
    nextAction: "Add weather provider and coarse location privacy controls.",
  },
  {
    id: "treatments",
    name: "Treatment Plan Center",
    route: "/treatments",
    category: "Treatment",
    description: "Plan creation, provider-directed flag, safety validation, schedule, check-ins, pause/resume, and archive.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["treatment_logs"],
    dataTables: ["treatment_plans", "treatment_checkins", "treatment_tasks"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Calendar UI", "provider review escalation", "task generation E2E"],
    nextAction: "Generate durable tasks from treatment schedules.",
  },
  {
    id: "treatment-checkins",
    name: "Treatment Check-ins",
    route: "/treatments/checkins",
    category: "Treatment",
    description: "Use, skipped, delayed, partial, stopped, irritation, and tolerance event capture.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["treatment_logs"],
    dataTables: ["treatment_checkins"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Active plan selector", "irritation escalation"],
    nextAction: "Wire active treatment plans into check-in form.",
  },
  {
    id: "tasks",
    name: "Task Board",
    route: "/tasks",
    category: "Gamification",
    description: "Daily tasks generated from real plans, logs, reports, and missing-data needs.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["tasks"],
    dataTables: ["treatment_tasks", "gamification", "badges", "user_badges"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: allSurfaces,
    missingSurfaces: ["Task generation rules", "streak state and completion E2E"],
    nextAction: "Derive streaks only after a canonical streak table is available.",
  },
  {
    id: "gamification",
    name: "Streaks, Badges, Ranks, and Pet",
    route: "/gamification",
    category: "Gamification",
    description: "Progress derived from real task completion, streak restore rules, badges, ranks, and pet state.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["tasks"],
    dataTables: ["treatment_tasks", "gamification", "badges", "user_badges"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "history", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Pet visual state", "rank progression from durable tasks"],
    nextAction: "Compute streak and badges only from completed durable tasks.",
  },
  {
    id: "reports",
    name: "Reports",
    route: "/reports",
    category: "Reports",
    description: "Dermatologist-ready report requests with missing-data sections and export-safe source references.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["reports"],
    dataTables: ["report_requests", "report_jobs", "report_files", "report_consent_snapshots"],
    storageBuckets: ["reports"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: [...allSurfaces, "export_state"],
    missingSurfaces: ["Production PDF storage", "signed download verification"],
    nextAction: "Verify report job persistence and private report file storage.",
  },
  {
    id: "report-history",
    name: "Report History",
    route: "/reports/history",
    category: "Reports",
    description: "Report request history, status, failures, and signed file access state.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["reports"],
    dataTables: ["report_requests", "report_jobs", "report_files"],
    storageBuckets: ["reports"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "history", "service_adapter", "persistence_contract", "export_state"],
    missingSurfaces: ["Live signed download", "provider-share workflow"],
    nextAction: "Validate report history API against production DB.",
  },
  {
    id: "report-export",
    name: "Report Export",
    route: "/reports/export",
    category: "Reports",
    description: "Report export request surface with consent snapshot, missing-data sections, and private file target.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: true,
    requiresConsentScopes: ["reports"],
    dataTables: ["report_requests", "report_files", "report_consent_snapshots"],
    storageBuckets: ["reports"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "export_state", "readiness_state"],
    missingSurfaces: ["Production PDF worker", "signed report file delivery"],
    nextAction: "Create report jobs with real source references and no generated filler sections.",
  },
  {
    id: "export",
    name: "Data Export",
    route: "/export",
    category: "Privacy",
    description: "User-controlled export requests for profile, logs, scans, reports, tasks, weather, and consents.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["export_requests", "export_files"],
    storageBuckets: ["exports"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract", "export_state"],
    missingSurfaces: ["Private export bucket verification", "file expiry cleanup"],
    nextAction: "Verify export request API and signed file delivery.",
  },
  {
    id: "delete-account",
    name: "Deletion Controls",
    route: "/delete-account",
    category: "Privacy",
    description: "Account/data deletion requests, export-first prompt, delayed purge, and audit events.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["deletion_requests", "deletion_audit_events"],
    storageBuckets: ["face-scans-raw", "reports", "skin-twin"],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "history", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Production purge worker", "cross-bucket deletion verification"],
    nextAction: "Verify deletion service against configured DB and private storage.",
  },
  {
    id: "research",
    name: "Research Network",
    route: "/research",
    category: "Research",
    description: "Personal learning versus anonymous network learning, raw image sharing, revocation, and contribution state.",
    prdPriority: "P1",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: ["anonymous_learning"],
    dataTables: ["consent_settings", "consent_audit_events"],
    storageBuckets: [],
    serviceStatus: "consent_required",
    readinessStatus: "consent_required",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Contribution ledger", "model update governance UI"],
    nextAction: "Persist anonymous learning revocation and derived-only contribution policy.",
  },
  {
    id: "settings",
    name: "Settings and Notifications",
    route: "/settings",
    category: "Account",
    description: "Notification preferences, accessibility settings, app privacy defaults, and release-readiness controls.",
    prdPriority: "P2",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["consent_settings"],
    storageBuckets: [],
    serviceStatus: "database_unavailable",
    readinessStatus: "insufficient_data",
    implementedSurfaces: ["route", "form", "service_adapter", "persistence_contract", "readiness_state"],
    missingSurfaces: ["Push notification provider", "accessibility preference persistence"],
    nextAction: "Connect notification preferences to native push readiness.",
  },
  {
    id: "native-mobile",
    name: "Native Mobile Readiness",
    route: "/mobile",
    category: "Native/Device",
    description: "Expo shell readiness, SecureStore auth storage, camera/gallery, location, notifications, and offline sync.",
    prdPriority: "P0",
    requiresAuth: false,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["ml_runtime_events"],
    storageBuckets: ["face-scans-raw"],
    serviceStatus: "not_configured",
    readinessStatus: "not_configured",
    implementedSurfaces: ["route", "service_adapter", "readiness_state"],
    missingSurfaces: ["Expo run validation", "SecureStore session E2E", "device permission tests"],
    nextAction: "Validate Expo shell and native secure storage on device/simulator.",
  },
  {
    id: "oauth-consent",
    name: "OAuth Consent",
    route: "/oauth/consent",
    category: "Privacy",
    description: "Account-gated consent screen with safe redirect handling and no fake token issuance.",
    prdPriority: "P0",
    requiresAuth: true,
    requiresOnboarding: false,
    requiresConsentScopes: [],
    dataTables: ["consent_audit_events"],
    storageBuckets: [],
    serviceStatus: "auth_required",
    readinessStatus: "auth_required",
    implementedSurfaces: ["route", "form", "service_adapter", "readiness_state"],
    missingSurfaces: ["Server OAuth continuation", "client registration management"],
    nextAction: "Complete backend OAuth authorization continuation.",
  },
];

export const moduleByRoute = new Map(ACNETREX_MODULES.map((module) => [module.route, module]));
export const moduleById = new Map(ACNETREX_MODULES.map((module) => [module.id, module]));

export function getModuleByPath(path: string): AcneTrexModule | undefined {
  const normalized = path === "/" ? path : path.replace(/\/+$/, "");
  return moduleByRoute.get(normalized);
}

export function modulesByCategory(): Record<ModuleCategory, AcneTrexModule[]> {
  const grouped: Record<ModuleCategory, AcneTrexModule[]> = {
    Account: [],
    "Daily Intelligence": [],
    "Face Intelligence": [],
    "Product Intelligence": [],
    "AI/ML Intelligence": [],
    Treatment: [],
    Reports: [],
    Privacy: [],
    Gamification: [],
    "Native/Device": [],
    Research: [],
  };

  for (const moduleConfig of ACNETREX_MODULES) {
    grouped[moduleConfig.category].push(moduleConfig);
  }

  return grouped;
}

export function completionSnapshot() {
  const total = ACNETREX_MODULES.length;
  const routed = ACNETREX_MODULES.filter((module) => module.implementedSurfaces.includes("route")).length;
  const withPersistenceContract = ACNETREX_MODULES.filter((module) =>
    module.implementedSurfaces.includes("persistence_contract"),
  ).length;
  const withAiContract = ACNETREX_MODULES.filter((module) =>
    module.implementedSurfaces.includes("ai_contract"),
  ).length;

  return {
    total,
    routed,
    withPersistenceContract,
    withAiContract,
    blockedByLiveInfrastructure: ACNETREX_MODULES.filter((module) =>
      ["database_unavailable", "not_configured", "ml_unavailable"].includes(module.serviceStatus),
    ).length,
  };
}
